<a href="https://colab.research.google.com/github/carlosLTorresULEAM/numpy-pandasIA/blob/main/Lecci%C3%B3n08_07_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importamos la biblioteca NumPy utilizando la instrucción import numpy as np.**

In [ ]:
import numpy as np

**Importe numpy como np y vea la versión**

In [ ]:
print(np.__version__)

1.25.2


**Crea una matriz 1D de números del 0 al 9**

In [ ]:
arr = np.arange(10)
print(arr)
#Este código crea un array de números enteros del 0 al 9 usando la función
#arange de NumPy, lo asigna a una variable llamada arr y luego lo imprime en la consola.

[0 1 2 3 4 5 6 7 8 9]


**Cree un vector aleatorio de tamaño 10 y reemplace el valor máximo por 0**

In [ ]:

z = np.random.random(10)
print(z)
# Reemplazamos el valor máximo por 0
z[z.argmax()] = 0
print(z)
#Este código genera un array de 10 números aleatorios entre 0 y 1, luego
#identifica el valor máximo y lo reemplaza por 0. Finalmente, imprime el array
#original y el array modificado.

[0.2600741  0.92991125 0.97790505 0.75278111 0.57826143 0.75645265
 0.81054989 0.37002571 0.91948521 0.71392284]
[0.2600741  0.92991125 0.         0.75278111 0.57826143 0.75645265
 0.81054989 0.37002571 0.91948521 0.71392284]


**Imprima el número 8 de la siguiente matriz:**
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])
#Este código crea un array NumPy de dos dimensiones, accede al elemento en la
#segunda fila y tercera columna, y luego imprime el valor de ese elemento (que es 8).

8


**Imprima los números [3, 4, 5] de la siguiente matriz:**
matriz = np.matriz([1,2,3,4,5,6,7])

In [ ]:
arr = np.arange(10)
print(arr)

z = np.random.random(10)
print(z)

z[z.argmax()] = 0
print(z)

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

#Este código demuestra la creación y manipulación de arrays NumPy para generar
#secuencias numéricas, acceder a elementos específicos y extraer subsecciones
#de arrays.

1.25.2
[0 1 2 3 4 5 6 7 8 9]
[0.79424779 0.66434571 0.11012836 0.56896468 0.77280703 0.7607648
 0.44515949 0.33682112 0.53749771 0.61809865]
[0.         0.66434571 0.11012836 0.56896468 0.77280703 0.7607648
 0.44515949 0.33682112 0.53749771 0.61809865]
8
[3 4 5]


**Imprima los últimos 4 números de la siguiente matriz:**
matriz = np.matriz([1,2,3,4,5,6,7])

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-4:])
#El código crea un array de números.
#Luego selecciona los últimos cuatro números del array.
#Finalmente, imprime estos últimos cuatro números.

[4 5 6 7]


**Crea una matriz numérica de 3 × 3 de todos los True**

In [ ]:
arr = np.full((3, 3), True, dtype=bool)
print(arr)
#El codigo realiza una matriz de 3x3 con los Trues

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Extrae todos los números impares de array**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]
#El código crea un nuevo array elementos_impares que contiene solo los elementos
#impares del arr original utilizando la selección condicional dentro de los corchetes.
#Finalmente, print(elementos_impares) muestra el array resultante que contiene los números impares.

array([1, 3, 5, 7, 9])

**Crea un vector con valores que van del 10 al 49 (★☆☆)**

In [ ]:
Z = np.arange(10,50)
print(Z)
#El código crea un array NumPy llamado Z que contiene todos los números enteros
#desde 10 hasta 49 (inclusive de 10 pero no 50).

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Invertir un vector (el primer elemento se convierte en el último)**

In [ ]:
arr = np.arange(10)
arr_reversed = arr[::-1]
print(arr_reversed)
#El código crea un array NumPy llamado arr con los números del 0 al 9. Luego,
#utilizando slicing invierte el orden de los elementos y lo almacena en un nuevo
#array llamado arr_reversed. Finalmente, imprime el array arr_reversed que
#contiene los elementos de arr en orden inverso

[9 8 7 6 5 4 3 2 1 0]


**Cree una matriz de 10x10 con valores enteros aleatorios y encuentre los valores mínimo y máximo**

In [ ]:

arr = np.random.randint(0, 100, size=(10, 10))

min_value = arr.min()
max_value = arr.max()

print("Array:")
print(arr)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)
#El código crea un array NumPy bidimensional (10x10) llamado arr con valores
#aleatorios entre 0 y 100 (exclusivo). Luego, encuentra el valor mínimo y máximo
#dentro del array y los almacena en variables separadas. Finalmente, imprime
#el array completo, el valor mínimo y el valor máximo.

Array:
[[35  6 74 17 91 89  5 91 77 94]
 [63 97  6 77 79 27 34 20 44 89]
 [49 90 30 85 91 49  3 44 26 64]
 [92 23 63 74 94 29 72 71 54  2]
 [20 71 29 17 88 89 96 80 81 53]
 [85 44 26 62 57 15 29 99 98  4]
 [20 25 90 98 87 95  1 83 69 84]
 [54 82 74 64 48 87 38 37 88 88]
 [11  4 47 15 95 86  9  3 86 32]
 [61 85 22 46 55 67 52 26 21 38]]

Minimum value: 1
Maximum value: 99


**Crea una matriz de 3x3x3 con valores aleatorios**

In [ ]:
arr = np.random.rand(3, 3, 3)
print(arr)
#El código crea un array NumPy tridimensional (3x3x3) llamado arr utilizando la
#función np.random.rand. El array se llena con números aleatorios distribuidos
#uniformemente entre 0 y 1 (exclusivo).
#Finalmente, se imprime el contenido del array arr en la consola.

[[[0.81265319 0.9125758  0.50526916]
  [0.11739192 0.24751588 0.49954466]
  [0.79260151 0.38822218 0.77128555]]

 [[0.90010596 0.62857139 0.28603713]
  [0.3612922  0.52267463 0.41837945]
  [0.02231172 0.70710206 0.95748378]]

 [[0.19986042 0.58649077 0.27431427]
  [0.03547453 0.6931092  0.1818524 ]
  [0.02740611 0.5765253  0.51026294]]]


**Reemplace todos los números impares en orden con -1**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)
#El código modifica un array NumPy existente, reemplazando todos los números
#impares con -1.
#Pasos:
#Creación del array: Se crea un array NumPy con los números enteros del 0 al 9.
#Selección y modificación: Se utilizan expresiones condicionales para
#identificar los números impares y reemplazarlos por -1 en el array original.
#Impresión: Se imprime el array modificado, mostrando los números impares
#reemplazados por -1.

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Crea una matriz de tipo float**

In [ ]:
arr = np.array([1.3, 2.5, 3.7, 4.2], dtype=np.float32)
print(arr)
#El código crea un array NumPy unidimensional con números de punto flotante y lo imprime.
#Pasos:
#Creación: Se crea un array NumPy con valores de punto flotante y tipo de dato float32.
#Impresión: Se imprime el contenido del array.

[1.3 2.5 3.7 4.2]


**Convierta una matriz 1D en una matriz 2D con 2 filas**

In [ ]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)  # -1 infiere el número de columnas en función del número de elementos y filas
print(arr_2d)
#El código crea un array NumPy unidimensional con números enteros del 0 al 9 y
#lo reestructura en un array bidimensional con 2 filas. La cantidad de columnas
#se calcula automáticamente para acomodar todos los elementos

[[0 1 2 3 4]
 [5 6 7 8 9]]


**How to find common values between two arrays?**

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

In [ ]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

common_values = np.intersect1d(Z1, Z2)
print("Common values:", common_values)
#El código genera dos arrays aleatorios con enteros del 0 al 9 (exclusivo) y
#luego encuentra los valores que son comunes a ambos.

Common values: [0 3 5 6]


**Considere dos matrices aleatorias A y B, verifique si son iguales**
A = np.aleatorio.randint(0,2,5)
B = np.aleatorio.randint(0,2,5)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
comparison = A == B
equal_arrays = comparison.all()
print(equal_arrays)
#El código genera dos arrays aleatorios del mismo tamaño y luego verifica si
#son exactamente iguales comparando cada elemento correspondiente. Se imprime
#"True" si los arrays son iguales, y "False" en caso contrario.

False


**Apilar matrices a y b verticalmente**

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print(c)
#El código crea dos arrays y luego los combina verticalmente en un nuevo array.

[[1 2 3]
 [4 5 6]]


**Apile las matrices a y b horizontalmente.**

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b))
print(c)
#El código crea dos arrays y luego los combina horizontalmente en un nuevo array.

[1 2 3 4 5 6]


**Obtenga todos los elementos entre 5 y 10 de la matriz tmp.**

In [ ]:
tmp = np.array([2, 6, 1, 9, 10, 3, 27])
result = tmp[(tmp > 5) & (tmp < 10)]
print(result)
#El código filtra un array NumPy para obtener un nuevo array que contiene solo
#los valores que están entre 5 y 10 (exclusivo).

**¿Cómo hacer una función de Python que maneje escalares para que funcione en matrices numerosas?**
Pista
Salida deseada:
a = np.matriz([5, 7, 9, 8, 6, 4, 5])
b = np.matriz([6, 3, 4, 8, 9, 7, 1])
par_max(a, b)
> matriz([ 6., 7., 9., 8., 9., 7., 5.])

In [ ]:
def pair_max(x, y):
  """
  Esta función toma dos arrays NumPy (x e y) como entrada y devuelve un nuevo array
  donde cada elemento es el máximo entre los elementos correspondientes en x e y.
  """
  return np.maximum(x, y)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a, b)
print(result)  # Salida: [ 6.  7.  9.  8.  9.  7.  5.]
#La función pair_max es útil para encontrar el valor máximo entre dos arrays NumPy del mismo tamaño.
#Se puede usar para comparar elementos correspondientes en dos arrays y seleccionar el mayor valor para cada par.

[6 7 9 8 9 7 5]


**Intercambie las columnas 1 y 2 en la matriz arr.**
Pista
Salida deseada:
[[0 2 1]
[3 5 4]
[6 8 7]]

In [ ]:
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0, 2]]
#El código crea un array NumPy 3x3 y luego selecciona columnas específicas en un orden personalizado.

**Cree una matriz 2D de forma 5x3 para contener números decimales aleatorios entre 5 y 10.**
Pista
La salida deseada debería ser como la siguiente:
[[8.50061025 9.10531502 6.85867783]
[ 9.76262069 9.87717411 7.13466701]
[7.48966403 8.33409158 6.16808631]
[7.75010551 9.94535696 5.27373226]
[8.0850361 5.56165518 7.31244004]]

In [ ]:
arr = np.random.uniform(5, 10, size=(5, 3))
print(arr)
#El código genera un array NumPy bidimensional con valores aleatorios uniformes
#entre 5 y 10, y luego lo imprime en la consola.

[[8.93439218 9.47564655 5.5572483 ]
 [5.80039307 8.41985107 8.5440045 ]
 [9.34439363 7.62292024 8.52177876]
 [6.13437524 7.56520707 9.57100006]
 [5.31079806 7.92053219 7.87776567]]
