<a href="https://colab.research.google.com/github/carlosLTorresULEAM/numpy-pandasIA/blob/main/Martes_01_07_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[0], a[1])
print(a[0:2])
print(a[1:])

a[1]=888
print(a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
11 22
[11 22]
[22 33]
[ 11 888  33]


In [ ]:
b=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(b.shape)
print(type(b))
print(b)

print(b[1,1])
aux=b[1:,1:].copy()
print(aux.shape)
print(aux)

print('ANTES....')
print(b)
print(aux)

aux[1,1]=1000

print('DESPUES...')
print(b)
print(aux)

(3, 3)
<class 'numpy.ndarray'>
[[11 22 33]
 [44 55 66]
 [77 88 99]]
55
(2, 2)
[[55 66]
 [88 99]]
ANTES....
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[55 66]
 [88 99]]
DESPUES...
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[  55   66]
 [  88 1000]]


In [ ]:
c=np.zeros((4,4))
print(c)
print(c.shape)

d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [ ]:
e=np.eye(3,3)
print(e) # Removed extra space before 'print'
f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
tmp1=np.random.randint(1,21, size=(4,4))
print(tmp1)
rows=np.array([0,1,2,0])
cols=np.arange(4)

print(rows)
print(cols)

[[15 11  2 20]
 [ 5 17  1  3]
 [17 12 17  2]
 [ 3  8 11 18]]
[0 1 2 0]
[0 1 2 3]


In [ ]:
tmp1[rows, cols]=100
print(tmp1)

[[100  11   2 100]
 [  5 100   1   3]
 [ 17  12 100   2]
 [  3   8  11  18]]


In [ ]:
tmp2=np.random.randint(20,50, size=(6,6))
print(tmp2)

[[48 29 26 31 42 32]
 [42 36 24 28 38 30]
 [21 41 26 40 34 27]
 [37 36 25 22 20 29]
 [23 29 47 31 24 28]
 [31 24 24 34 34 35]]


In [ ]:
mask = tmp2 > 45
print(mask)
elemay = tmp2[mask]

print("Elementos mayores a 45:")
print(elemay)

[[ True False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False  True False False False]
 [False False False False False False]]
Elementos mayores a 45:
[48 47]


In [ ]:
tmp3=np.random.randint(1,100, size=(10,10))
print(tmp3)

[[88  7 47 34 77 28  3 99 13 28]
 [54 93 75 84  6 14 58 41 11 61]
 [29  2 85 54 77 35 62 84 70 39]
 [ 2 12 69 74 21 14  1 81 63 79]
 [88 42 84 44 92 30 43  9 10 23]
 [19 49 21  6 78 34 41 26  7 64]
 [98 71 27 62 28 32 95 55  9 78]
 [60 81 63 47 75 99 23 39 66 29]
 [80 41 93 40 88 83 38 11 40 92]
 [87 69 80 25 28 70 99 11 20 61]]


In [ ]:
mask2 = ((tmp3%2)==0)
# print(mask2)
elepar = tmp3[mask2]

print("Elementos pares:")
print(elepar)


Elementos pares:
[88 34 28 28 54 84  6 14 58  2 54 62 84 70  2 12 74 14 88 42 84 44 92 30
 10  6 78 34 26 64 98 62 28 32 78 60 66 80 40 88 38 40 92 80 28 70 20]


In [ ]:
tmp4=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp4.dtype)
print(tmp4)


float64
[1. 2. 3. 4. 5.]


In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x)
print(y)
print('SUMA')
print(np.add(x,y))
print('RESTA')
print(np.subtract(x,y))
print('MULTIPLICACION')
print(np.multiply(x,y))
print('DIVISION')
print(np.divide(x,y))
print('RAIZ')
print(np.sqrt(x))
print('POTENCIA')
print(np.power(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
SUMA
[[ 6  8]
 [10 12]]
RESTA
[[-4 -4]
 [-4 -4]]
MULTIPLICACION
[[ 5 12]
 [21 32]]
DIVISION
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
RAIZ
[[1.         1.41421356]
 [1.73205081 2.        ]]
POTENCIA
[[    1    64]
 [ 2187 65536]]


In [ ]:
tmp5=np.random.randint(1,10, size=(2,5))
print(tmp5)
aux=tmp5.mean()
print(aux)

[[9 8 6 8 9]
 [5 5 2 6 5]]
6.3


In [ ]:
print(tmp5.mean(axis=1))
print(tmp5.mean(axis=0))

[8.  4.6]
[7.  6.5 4.  7.  7. ]
