<a href="https://colab.research.google.com/github/carlosLTorresULEAM/numpy-pandasIA/blob/main/Martes_02_07_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.random.randint(1, 10, (3, 4))
print(a)
tmp=np.mean(a)
print(tmp)
print(a.mean())
tmp=a.mean(axis=1)
print(tmp)

aux=a.sum()
print(aux)
medianValue=np.median(a,axis=1)
print(medianValue)


[[9 6 8 5]
 [2 6 9 8]
 [8 3 2 7]]
6.083333333333333
6.083333333333333
[7.   6.25 5.  ]
73
[7. 7. 5.]


In [ ]:
#SORTING
b=np.random.randn(10)
print(b)
print(b.shape)
b.sort()
print(b)

[-0.36485152  0.30146646  0.04397406 -0.75079799 -0.37645747  0.81588242
 -0.35737883 -0.06455737 -0.75014001 -1.06087298]
(10,)
[-1.06087298 -0.75079799 -0.75014001 -0.37645747 -0.36485152 -0.35737883
 -0.06455737  0.04397406  0.30146646  0.81588242]


In [ ]:
c=np.array([2,3,4,2,5,3,5])
print(np.unique(c))

[2 3 4 5]


In [ ]:
string1=np.array(['desk','chair','bulb',])
string2=np.array(['lamp','bulb','chair',])

tmp1=np.intersect1d(string1, string2)
print(tmp1)

tmp2=np.union1d(string1, string2)
print(tmp2)

tmp3=np.setdiff1d(string1, string2)
print(tmp3)

tmp4=np.in1d(string1, string2)
print(tmp4)

['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


In [ ]:
#BROADCASTING
print('1')
aux = np.zeros((4,3))
print(aux)
print('2')
replicate=np.array([1,2,1])
aux=aux+replicate
print(aux)
print('3')
replicate=np.array([[10,10,10]])
print(replicate.shape)
print('4')
replicateCol=np.reshape(replicate,(3,1))
print(replicateCol.shape)
print('5')
aux = np.zeros((3,3))
aux=aux+replicateCol
print(aux)


1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
3
(1, 3)
4
(3, 1)
5
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [ ]:
vector=np.array([45])
matixZeros=np.zeros((5,5))
print(matixZeros)
print(matixZeros+vector)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
